variable "env" {}
variable "vpc" {}
variable "project_name" {}
variable "rds" {}
variable "kms_key_id" {}
variable "instance_type" {}
variable "app_port_backend" {}
variable "bastion_block" {}
variable "instance_capacity" {}
variable "app_port_frontend" {}
variable "certificate_arn" {}