variable "env" {}
variable "component" {}
variable "project_name" {}
variable "instance_capacity" {}
variable "instance_type" {}
variable "app_port" {}
variable "bastion_block" {}
variable "vpc_id" {}
variable "sg_cidr_blocks" {}
variable "vpc_zone_identifier" {}
variable "parameters" {}